name: obscure_widget
description: ObscureWidget blur its child when screen is being captured.
version: 0.0.1
homepage: https://github.com/imSanjaySoni/ObscureWidget
repository: https://github.com/imSanjaySoni/ObscureWidget.git

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      ios:
        pluginClass: ObscureWidgetPlugin
        sharedDarwinSource: true
