name: obscure_widget
description: ObscureWidget blurs its child when the screen is being captured. gives extra control to add custom handling when the screen is recorded.
homepage: https://github.com/imSanjaySoni/ObscureWidget
repository: https://github.com/imSanjaySoni/ObscureWidget/tree/main
issue_tracker: https://github.com/imSanjaySoni/ObscureWidget/issues
documentation: https://github.com/imSanjaySoni/ObscureWidget/tree/main#readme

version: 0.0.3

environment:
  sdk: '>=2.14.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      ios:
        pluginClass: ObscureWidgetPlugin
        sharedDarwinSource: true

screenshots:
  - description: The obscure_widget plugin logo.
    path: screenshots/logo.png